src/main/models.py
# -*- coding: utf-8 -*-

from sqlalchemy import Column

from ..extensions import db

from ..utils import get_current_time

from ..users import AdminRequired

from flask_login import current_user
from flask_admin.contrib import sqla


class ContactUs(db.Model):

    __tablename__ = 'contactus'

    id = Column(db.Integer, primary_key=True)
    name = Column(db.String(64), nullable=False)
    email = Column(db.String(64), nullable=False)
    deck_id = Column(db.Integer, nullable=True)
    subject = Column(db.String(128), nullable=False)
    message = Column(db.String(2048), nullable=False)

    received_time = Column(db.DateTime, default=get_current_time)

    def __unicode__(self):
        _str = '%s. %s %s' % (self.id, self.name, self.email)
        return str(_str)


# Customized ContactUs model admin
class ContactUsView(AdminRequired, sqla.ModelView):
    column_sortable_list = ('id', 'name', 'email', 'received_time')
    column_filters = ('id', 'name', 'email', 'received_time')

    def __init__(self, session):
        super(ContactUsView, self).__init__(ContactUs, session)

src/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField, TextAreaField, EmailField)
from wtforms.validators import InputRequired, Length, Email

class ContactUsForm(FlaskForm):
    name = StringField('Name', [InputRequired(), Length(max=64)])
    email = EmailField('Your Email', [InputRequired(), Email(), Length(max=64)])
    subject = StringField('Subject', [InputRequired(), Length(5, 128)])
    message = TextAreaField('Your Message', [InputRequired(), Length(10, 1024)])
    submit = SubmitField('Submit')

src/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, SelectField, SubmitField,
                     BooleanField, TextAreaField, IntegerField)
from wtforms.validators import ValidationError, DataRequired, URL, Length, Regexp, Optional
from ..models import Post, Deck
from ..constants import CHOICES, REASONS
import re
from ..constants import (
    URL_LEN_MAX,
    POST_TITLE_LEN_MIN,
    POST_TITLE_LEN_MAX,
    POST_DESCRIPTION_LEN_MIN,
    POST_DESCRIPTION_LEN_MAX,
    DECK_FIELDS_LEN_MAX,
    DECK_TITLE_LEN_MIN,
    DECK_TITLE_LEN_MAX,
    DECK_DESCRIPTION_LEN_MIN,
    DECK_DESCRIPTION_LEN_MAX,
    REPORT_DESCRIPTION_LEN_MIN,
    REPORT_DESCRIPTION_LEN_MAX
)

error_msg = f"This field can only contain letters and numbers"

class PostForm(FlaskForm):
    title = StringField('Title',
                        validators=[DataRequired(), Length(min=POST_TITLE_LEN_MIN,
                                                           max=POST_TITLE_LEN_MAX),
                                    Regexp(r'^[ \w\d]+$',0,error_msg)])
    description = TextAreaField('Description',
                              validators=[DataRequired(), Length(min=POST_DESCRIPTION_LEN_MIN,
                                                                 max=POST_DESCRIPTION_LEN_MAX),
                                          Regexp(r'^[ \w\d]+$',0,error_msg)])
    url = StringField('URL', validators=[DataRequired(), URL(), Length(max=URL_LEN_MAX)])
    field = SelectField('field',choices=[], validate_choice=True)
    submit = SubmitField('Add')


class DeckForm(FlaskForm):
    deck_name = StringField('Deck Title',
                        validators=[DataRequired(), Length(min=DECK_TITLE_LEN_MIN,max=DECK_TITLE_LEN_MAX),
                                    Regexp(r'^[ \w\d]+$',0,error_msg)])
    deck_description = TextAreaField('Deck description',
                                   validators=[Length(min=DECK_DESCRIPTION_LEN_MIN,max=DECK_DESCRIPTION_LEN_MAX),
                                               Regexp(r'^[ \w\d]*$',0,error_msg)])
    category = SelectField('Categories', choices=CHOICES.keys())
    fields = TextAreaField('Table Fields', validators=[DataRequired(), Length(max=DECK_FIELDS_LEN_MAX),
                                                       Regexp(r'^[ \w\d]+$',0,error_msg)])
    public = BooleanField('Public')
    submit = SubmitField('Create Deck')

    def validate_fields(self, field):
        long_fields = [i for i in field.data.split() if len(i) >= 20]
        if long_fields:
            error_msg = f"Each field can have only up to 15 characters"
            raise ValidationError(error_msg)

class ReportForm(FlaskForm):
    reason = SelectField('Reason', choices=REASONS.values())
    deck_id = IntegerField([Optional()])
    description = TextAreaField('Description',
                              validators=[DataRequired(), Length(min=REPORT_DESCRIPTION_LEN_MIN,
                                                                 max=REPORT_DESCRIPTION_LEN_MAX),
                                          Regexp(r'^[ \w\d]+$',0,error_msg)])

class VoteForm(FlaskForm):
    post_id = IntegerField('Post ID')
    vote_type = IntegerField('Vote Type', validators=[DataRequired()])

class UrlForm(FlaskForm):
    url = StringField('URL',
                      validators=[DataRequired(), URL(), Length(max=URL_LEN_MAX)])

class LikeForm(FlaskForm):
    like_id = IntegerField('Like id')

src/__init__.py
from flask import Flask, request, render_template, has_request_context

from werkzeug.exceptions import HTTPException

from .extensions import db, csrf, htmx, mail, login_manager, admin

from .utils import (pretty_date, get_random_urlsafe_string,
                    check_none_values)
from .config import config

from .users.routes import users
from .posts import posts
from .main import main

__all__ = ['create_app']

BLUEPRINTS = (
    posts,
    main,
    users
)

def create_app(config_name=None):

    blueprints = BLUEPRINTS

    app = Flask(__name__, instance_relative_config=True)

    configure_app(app, config_name)
    configure_extensions(app)
    configure_template_filters(app)
    configure_error_handlers(app)
    configure_blueprints(app, blueprints)

    return app

def configure_app(app, config_name=None):

    config_name = config_name or 'default'

    # A function that checks if there is an empty value in the config
    check_none_values(config[config_name])

    app.config.from_object(config[config_name])

    if hasattr(config[config_name], 'init_app'):
        config[config_name].init_app(app)

    print('=' * 10, f"> Running in {config_name} mode!\n")

def configure_template_filters(app):
    """
    A little cleanup after jinja template rendering
    : removing spaces, and striping new lines
    """
    app.jinja_env.trim_blocks = True
    app.jinja_env.lstrip_blocks = True
    strip_trailing_newlines = True

    @app.template_filter()
    def _pretty_date(value):
        return pretty_date(value)
    @app.template_filter()
    def format_date(value, format='%Y-%m-%d'):
        return value.strftime(format)

def configure_blueprints(app, blueprints):
    for blueprint in blueprints:
        app.register_blueprint(blueprint)

def configure_extensions(app):
    db.init_app(app)
    csrf.init_app(app)
    htmx.init_app(app)
    mail.init_app(app)
    admin.init_app(app)
    login_manager.init_app(app)

def configure_error_handlers(app):
    @app.errorhandler(Exception)
    def handle_error(error):
        if not isinstance(error, HTTPException):
            if not app.debug:
                return render_template('errors/500.html'), 500
            raise
        return render_template('errors/errors.html', error=error), error.code
    @app.errorhandler(404)
    def custom_error_404(error):
        return render_template('errors/404.html', error=error), error.code

src/main/__init__.py
from .routes import main
from .models import ContactUsView, ContactUs

src/posts/__init__.py
from .routes import posts

src/users/__init__.py
from .models import User, UserView, AdminRequired
from .constants import USER_ROLE, ADMIN, USER, USER_STATUS, NEW, ACTIVE

src/users/routes.py
from flask import (render_template, url_for, flash, Response, current_app,
                   abort, redirect, request, Blueprint)

from flask_login import (login_required, login_user, current_user,
                         logout_user, login_fresh, user_logged_in,
                         user_login_confirmed)

from flask_htmx import make_response as htmx_make_response

from .forms import (SingupForm, LoginForm,
                    RecoverPasswordForm,
                    ChangePasswordForm,
                    UpdateSettingsForm,
                    UserChangePasswordForm)

from .utils import (get_data_from_hash, generate_hash,
                    confirm_user_mail, send_email)

from . import User, ACTIVE

from ..utils import rs, get_uuid

from ..modules.http import url_has_allowed_host_and_scheme

from ..decorators import requires_fresh_session

from ..extensions import db, htmx, login_manager

from ..models import Deck

users = Blueprint('users', __name__)

@users.route("/account")
@login_required
def account():
    likes = sum([deck.likes for deck in current_user.decks])
    s = request.args.get('s')
    if not s:
        return render_template("user/user.html" ,likes=likes)

    template_mapping = {
        'profile': 'user/profile.html',
        'settings': 'user/settings.html',
        'danger_zone': 'user/danger_zone.html'
    }

    template = template_mapping.get(s)

    if template and htmx:
        return render_template(template, likes=likes)
    abort(400)

@users.route("/user/gravatar", methods=['PUT'])
@login_required
def user_gravatar():
    real_email_hash = True if request.form.get('reh') else False
    if real_email_hash != current_user.real_email_hash:
        current_user.real_email_hash = real_email_hash
        db.session.add(current_user)
        db.session.commit()
        flash("Avatar settings changed", "success")
        return htmx_make_response(location=url_for('users.account'))
    abort(400)

@users.route('/delete/account', methods=['DELETE'])
@login_required
@requires_fresh_session
def delete_account():
    try:
        db.session.delete(current_user)
        db.session.commit()
        flash("Your account was successfully deleted", "success")
        logout_user()
        return htmx_make_response(refresh=True)
    except:
        abort(400)

@users.route('/delete/decks', methods=["DELETE"])
@login_required
@requires_fresh_session
def delete_decks():
    decks = Deck.query.filter_by(user_id=current_user.id)
    if decks.count() != 0:
        decks.delete()
        db.session.commit()
        flash("All the decks were deleted", "success")
        return htmx_make_response(location=url_for('posts.decks'))

    flash("You don't have any deck yet!", "error")
    return htmx_make_response(location=url_for('posts.decks'))

@users.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = SingupForm()

    if form.validate_on_submit():
        user = User()
        user.status_code = 1
        user.account_type = 0
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()

        confirm_user_mail(form.username.data, form.email.data, 'Confirm your account for ',
                          'email_templates/html/_confirm_account.html',
                          'email_templates/txt/_confirm_account.txt')

        flash('Confirmation email sent to ' + form.email.data + ' Please verify!', 'success')
        if htmx:
            return htmx_make_response(redirect=url_for('users.login'))
        return redirect(url_for('users.login'))

    if htmx:
        return render_template("partials/user/signup.html", form=form, _active_signup=True,
                               SITE_KEY=current_app.config['TURNSTILE_SITE_KEY'])
    return render_template('user/signup.html', form=form, _active_signup=True,
                           SITE_KEY=current_app.config['TURNSTILE_SITE_KEY'])


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated and login_fresh():
        flash("You are already logged in!", "notice")
        return redirect(url_for('main.home'))

    next=request.args.get('next', url_for('posts.decks'))

    if not url_has_allowed_host_and_scheme(next, request.host):
        return abort(400)

    form = LoginForm(login=request.args.get('login', None), next=next)

    login_failed=False

    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.email.data, form.password.data)

        if user and authenticated:

            if user.status_code != 2:
                flash("Please verify your email address to continue", "error")
                return redirect(url_for('users.login'))

            remember = True if request.form.get('remember') else False

            if login_user(user, remember=remember):
                flash("Logged in", 'success')
            if htmx:
                return htmx_make_response(redirect=next)
            return redirect(next)
        else:
            login_failed=True
            flash('Invalid username or password', 'error')

    resp = {
        'form':form,
        'htmx': htmx,
        'login_failed': login_failed
    }

    if htmx:
        return render_template("partials/user/login.html", **resp)
    return render_template("user/login.html", **resp)

@users.route("/logout")
def logout():
    if not current_user.is_authenticated:
        return redirect(url_for('main.home'))
    logout_user()
    flash("Logged out!", "success")
    return redirect(url_for('main.home'))

@users.route('/confirm/account/<secretstring>', methods=['GET', 'POST'])
def confirm_account(secretstring):
    uname, uemail = get_data_from_hash(secretstring, salt="confirm_account")
    user = User.query.filter_by(username=uname).first_or_404()
    if user.email != uemail:
        # means the user already exists ... he only sent the request to change his email account ...
        user.email = uemail
        db.session.add(user)
        db.session.commit()
        flash("Your email was successfully changed", "success")
        return redirect(url_for('main.home'))
    user.status_code = ACTIVE
    db.session.add(user)
    db.session.commit()
    if user_login_confirmed:
        flash('Your account was confirmed succsessfully!!', 'success')
    else:
        flash('We failed to confirm your account :/', 'error')

    return redirect(url_for('users.login'))

@users.route('/reset/password', methods=['GET', 'POST'])
def reset_password():
    form = RecoverPasswordForm()

    if request.method == "POST":
        if form.validate_on_submit():
            user = User.query.filter(User.email.ilike(form.email.data)).first()

            if user:
                user.email_activation_key = get_uuid()
                db.session.add(user)
                db.session.commit()
                email = generate_hash(user.email, salt="reset_password")
                subject = 'Reset your password in ' + current_app.config['PROJECT_NAME']
                url = url_for('users.change_password', email=email,
                              email_activation_key=user.email_activation_key, _external=True)
                html = render_template('email_templates/html/_reset_password.html', project=current_app.config['PROJECT_NAME'],
                                       username=user.username, url=url)
                text = render_template('email_templates/txt/_reset_password.txt', project=current_app.config['PROJECT_NAME'],
                                       username=user.username, url=url)

                send_email(subject, html, text, user.email)
                flash('Please see your email for instructions on how to access your account', 'success')

                if htmx:
                    return htmx_make_response(redirect=url_for('users.login'))

                return redirect(url_for('users.login'))
            else:
                flash('Sorry, no user found for that email address', 'error')
        flash("Please provide a valid email address!", "error")
    if htmx:
        return htmx_make_response(redirect=url_for('users.login'))
    return render_template('user/reset_password.html', form=form)

@users.route('/change/password', methods=['GET', 'POST'])
@requires_fresh_session
def change_password():
    email = get_data_from_hash(request.args.get("email"), salt="change_password")
    form = ChangePasswordForm(email_activation_key=request.args.get('email_activation_key'), email=email)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data, email_activation_key=form.email_activation_key.data).first()
        if user:
            user.password = form.password.data
            user.email_activation_key = None
            db.session.add(user)
            db.session.commit()
            flash("Your password has been changed, log in again", "success")
            return redirect(url_for("users.login"))
        flash("User not found :/", "error")
    return render_template("user/change_password.html", form=form)

@users.route("/change/password/settings", methods=['POST', 'GET'])
@login_required
def user_change_password():
    if not htmx:
        abort(400)
    form = UserChangePasswordForm()
    if form.validate_on_submit():
        current_user.password = form.password.data
        db.session.add(current_user)
        db.session.commit()
        flash("Your password was changed successfully", "success")
        return htmx_make_response(location=url_for('users.account'))
    return render_template("partials/user_change_password.html", form=form)

@users.route('/update/settings', methods=['GET', 'POST'])
@login_required
@requires_fresh_session
def update_settings():
    form = UpdateSettingsForm()
    if not htmx:
        abort(400)
    if request.method == "POST":
        if form.validate_on_submit():
            if form.email.data != current_user.email:

src/templates/user/change_password.html
{% from "macros/_form.html" import render_form %}

{% extends "layout.html" %}

{% set title = "Change your password" %}
{% set description = "Change your password .." %}
{% set keywords = "change password" %} 

{% block h1 %}
<h1>Change password</h1>
{% endblock h1 %}

{% block content %}
  <div class="rel centered-content">
      {{ render_form(url_for('users.change_password'), form)}}
  </div>
{% endblock %}

src/templates/user/danger_zone.html
<div class="tab-list" role="tablist">
    <button hx-get="{{ url_for('users.account', s='profile') }}" class="tab" aria-selected="false" autofocus="false" role="tab" aria-controls="tab-content">Profile</button>
    <button hx-get="{{ url_for('users.account', s='settings') }}" role="tab" aria-selected="false" aria-controls="tab-content">Settings</button>
    <button hx-get="{{ url_for('users.account', s='danger_zone') }}" class="selected" aria-selected="true" autofocus="true" role="tab" role="tab" aria-controls="tab-content">Danger zone</button>
</div>

<h3>Danger zone:</h3>
<div class="is-small m-8 date">
	Proceed with caution ! All your decks and posts will be <u>permantly</u> deleted.
</div>
<div class="centered-content m-8">
	<div class="block">
		<div class="box error p-10 m-8" hx-delete="{{url_for('users.delete_decks')}}" hx-vals='{"csrf_token": "{{csrf_token()}}"}' hx-confirm="You are sure you want to permantely delete your decks?">
			Delete all decks
		</div>
		<div class="box error p-10 m-8" hx-delete="{{url_for('users.delete_account')}}" hx-vals='{"csrf_token": "{{csrf_token()}}"}' hx-confirm="Are you sure you want to permantely delete your account? All decks and posts will be lost.">
			Delete account
		</div>
	</div>
</div>

src/templates/user/login.html
{% extends "layout.html" %}

{% set title = "Login" %}
{% set description = "Secure login. Access your account now." %}
{% set keywords = "login, sign in, access account" %} 

{% block h1 %}
<h1>Login</h1>
{% endblock h1 %}

{% block content %}
{% include "partials/user/login.html" %}
{% endblock content %}

src/templates/user/reset_password.html
{% from 'macros/macros.html' import render_field %}
{% extends "layout.html" %}

{% set title = "Reset your password" %}
{% set description = "We can help you reset your password and security info. First, enter your email and follow the instructions we will send to you!" %}
{% set keywords = "reset password" %} 

{% block h1 %}
<h1>Reset your password</h1>
<p>We can help you reset your password and security info.
First, enter your email and follow the instructions we will send to you!</p>
{% endblock h1 %}

{% block content %}

<div id="form" class="rel centered-content">
    <form method="POST" action="{{url_for('users.reset_password')}}">
        <fieldset class="notice">
        {{ form.hidden_tag() }}
        {{ render_field(form.email,'Email', placeholder="email@example.org") }}
        <button hx-indicator="#spinner" hx-swap="outerHTML" hx-post="{{ url_for('users.reset_password') }}" hx-target="#form" class="gbf p-10" id="submit" type="submit" name="submit">
            Reset Password
            <svg id="spinner" class="spinner" width="25px" height="25px" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" fill="none">
                <g fill="var(--bg)" fill-rule="evenodd" clip-rule="evenodd">
                <path d="M8 1.5a6.5 6.5 0 100 13 6.5 6.5 0 000-13zM0 8a8 8 0 1116 0A8 8 0 010 8z" opacity=".2"/>
                <path d="M7.25.75A.75.75 0 018 0a8 8 0 018 8 .75.75 0 01-1.5 0A6.5 6.5 0 008 1.5a.75.75 0 01-.75-.75z"/>
                </g>
            </svg>
        </button>
        </fieldset>
    </form>
</div>

{% endblock content %}

src/templates/user/settings.html
{% from "macros/_form.html" import render_form %}
<div class="tab-list" role="tablist">
  <button hx-get="{{ url_for('users.account', s='profile') }}" aria-selected="false" autofocus="false" role="tab" aria-controls="tab-content">Profile</button>
  <button hx-get="{{ url_for('users.account', s='settings') }}" class="selected" aria-selected="true" autofocus="true" role="tab" aria-selected="false" aria-controls="tab-content">Settings</button>
  <button hx-get="{{ url_for('users.account', s='danger_zone') }}" role="tab" aria-selected="false" aria-controls="tab-content">Danger zone</button>
</div>
<h3>Gravatar</h3>
<div class="block">
  <label class="toggle">
          <input hx-put="{{ url_for('users.user_gravatar') }}" hx-target="#htmx-flashed" class="toggle-checkbox" hx-vals='{"csrf_token": "{{csrf_token()}}"}' value="True" name="reh" type="checkbox" id="reh" {% if current_user.real_email_hash %}checked{% endif %}>
          <div class="toggle-switch"></div>
          <span class="toggle-label">Use email for the avatar</span>
   </label>
  <div class="is-small m-8 date">
    Your email is not used for the avatar by default but rather a random hash.
  </div>
  <div>
    <details>
      <summary class="is-small">What is the avatar?</summary>
      <p>The avatar is a small profile picture associated with your account. If you have an account on gravatar.com and have enabled the option, it will display your profile picture from there.</p>
      <p>Please note that by default, the option to display the Gravatar profile picture is disabled.</p>
    </details>
  </div>
</div>
<h3>Account</h3>
<div hx-get="{{ url_for('users.update_settings') }}" hx-trigger="load delay:100ms" hx-target="this" hx-swap="innerHTML"></div>
<h3>Security</h3>
<div hx-get="{{ url_for('users.user_change_password') }}" hx-trigger="load delay:200ms" hx-target="this" hx-swap="innerHTML"></div>

src/templates/user/signup.html
{% from 'macros/macros.html' import render_field %}
{% extends "layout.html" %}
{% set title = "SignUp" %}
{% set description = "Sign up now to unlock exclusive features and personalized experiences." %}
{% set keywords = "signup, join, register" %} 
{% block h1 %}
<h1>Sign Up</h1>
{% endblock h1 %}
{% block content %}
{% include "partials/user/signup.html" %}
{% endblock content %}

src/templates/user/user.html
{% set title = "Account" %}
{% set description = "Change the user settings, gravar and other security settings." %}
{% set keywords = "account, settings, delete account, remove decks" %} 

{% extends "layout.html" %}

{% block h1 %}
<h1>Account</h1>
{% endblock h1 %}

{% block content %}

{% include "partials/nojs.html" %}

<div id="tabs" hx-target="this" hx-swap="innerHTML" class="">
  <div id="tab-content" role="tabpanel" class="tab-content">
    <div id="tabs" hx-get="{{ url_for('users.account', s='profile') }}" hx-trigger="load delay:100ms" hx-target="#tabs" hx-swap="innerHTML"></div>
   </div>
</div>


{% endblock content %}

src/templates/user/user_change_password.html
{% from 'macros/macros.html' import render_field %}

<p>Don't remember your password ? You can reset it <a href="{{url_for('users.reset_password')}}">here</a></p>
<div id="password_form" class="rel">
    {{ render_field(form.current_password,'Current Password', placeholder="Your current password") }}
    {{ render_field(form.password,'Password', placeholder="password") }}
    {{ render_field(form.confirm_password,'Confirm password', placeholder="Confirm password") }}
    <button
      hx-target="#password_form"
      type="submit"
      >Change Password</button>
</div>