src/__init__.py
from flask import Flask, request, render_template, has_request_context

from werkzeug.exceptions import HTTPException

from .extensions import db, csrf, htmx, mail, login_manager, admin

from .utils import (pretty_date, get_random_urlsafe_string,
                    check_none_values)
from .config import config

from .users.routes import users
from .posts import posts
from .main import main

__all__ = ['create_app']

BLUEPRINTS = (
    posts,
    main,
    users
)

def create_app(config_name=None):

    blueprints = BLUEPRINTS

    app = Flask(__name__, instance_relative_config=True)

    configure_app(app, config_name)
    configure_extensions(app)
    configure_template_filters(app)
    configure_error_handlers(app)
    configure_blueprints(app, blueprints)

    return app

def configure_app(app, config_name=None):

    config_name = config_name or 'default'

    # A function that checks if there is an empty value in the config
    check_none_values(config[config_name])

    app.config.from_object(config[config_name])

    if hasattr(config[config_name], 'init_app'):
        config[config_name].init_app(app)

    print('=' * 10, f"> Running in {config_name} mode!\n")

def configure_template_filters(app):
    """
    A little cleanup after jinja template rendering
    : removing spaces, and striping new lines
    """
    app.jinja_env.trim_blocks = True
    app.jinja_env.lstrip_blocks = True
    strip_trailing_newlines = True

    @app.template_filter()
    def _pretty_date(value):
        return pretty_date(value)
    @app.template_filter()
    def format_date(value, format='%Y-%m-%d'):
        return value.strftime(format)

def configure_blueprints(app, blueprints):
    for blueprint in blueprints:
        app.register_blueprint(blueprint)

def configure_extensions(app):
    db.init_app(app)
    csrf.init_app(app)
    htmx.init_app(app)
    mail.init_app(app)
    admin.init_app(app)
    login_manager.init_app(app)

def configure_error_handlers(app):
    @app.errorhandler(Exception)
    def handle_error(error):
        if not isinstance(error, HTTPException):
            if not app.debug:
                return render_template('errors/500.html'), 500
            raise
        return render_template('errors/errors.html', error=error), error.code
    @app.errorhandler(404)
    def custom_error_404(error):
        return render_template('errors/404.html', error=error), error.code

src/main/__init__.py
from .routes import main
from .models import ContactUsView, ContactUs

src/main/routes.py
from flask import (render_template, request, Blueprint,
                   url_for, flash, abort, session, redirect, current_app)

from flask_login import current_user, user_logged_in

from flask_htmx import make_response as htmx_make_response

from .forms import ContactUsForm

from .models import ContactUs

from ..models import Deck, Post

from ..extensions import db, htmx

from ..modules.http import url_has_allowed_host_and_scheme

from ..utils import (get_user_id, validate_user_input,
                     turnstile_verify)

from sqlalchemy import or_

from ..constants import (
    DECK_TITLE_LENGTH,
    PER_PAGE_POST,
    PER_PAGE_DECK,
    QUERY_LEN_MAX,
    CHOICES
)

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/<int:page>")
def home(page=1):
    deck = Deck.query.filter_by(public=True).order_by(Deck.likes.desc()).\
        paginate(page=page, per_page=PER_PAGE_DECK)

    data = {
        'deck': deck,
        'CHOICES': CHOICES,
        'PER_PAGE_DECK': PER_PAGE_DECK,
        'DECK_TITLE_LENGTH': DECK_TITLE_LENGTH
    }

    return render_template("home.html", **data)

@main.route('/category/<string:by>', defaults={'page': 1})
@main.route("/category/<string:by>/<int:page>")
def filter_by(by=None, page=None):
    if by in CHOICES:
        deck = Deck.query.filter_by(public=True, category=by).\
            paginate(page=page, per_page=PER_PAGE_DECK)
        if not deck.items:
            flash(f"No deck in this Category found!", "notice")
        return render_template('home.html', deck=deck, CHOICES=CHOICES,
                               PER_PAGE_DECK=PER_PAGE_DECK,
                               DECK_TITLE_LENGTH=DECK_TITLE_LENGTH, filter_by=CHOICES[by])
    abort(404)

@main.route('/search/', defaults={'select': 'deck_name', 'page': 1}, methods=['GET', 'POST'])
@main.route('/search/<string:select>/', defaults={'page': 1})
@main.route('/search/<string:select>/<int:page>/')
def search(select, page):
    user_id = get_user_id()
    template="search_decks.html"
    results=None
    per_page=0

    if request.method == "GET":
        query = request.args.get("q", "None")
    elif request.method == "POST":
        select=request.form.get("select")
        query = request.form.get("q", "None")

    try:
        validate_user_input(query, QUERY_LEN_MAX)
    except Exception as e:
        flash(str(e), "error")

    def deck_query():
        global PER_PAGE_DECK
        return per_page, Deck.query.filter(
            (Deck.public == True) | (Deck.user_id == user_id),
            Deck.deck_name.ilike(f'%{query}%')
        ).paginate(page=page, per_page=PER_PAGE_DECK)
    def post_query():
        global PER_PAGE_POST
        return per_page,(
            Post.query
            .join(Deck)
            .filter(
                (Deck.public == True) | (Deck.user_id == user_id),
                or_(
                    (select == 'title' and Post.title.ilike(f'%{query}%')),
                    (select == 'description' and Post.description.ilike(f'%{query}%'))
                )
            )
            .paginate(page=page, per_page=PER_PAGE_POST)
        )

    if select == 'deck_name':
        per_page, results = deck_query()
        template='search_decks.html'
    elif select in ['title', 'description']:
        template='search_posts.html'
        per_page, results = post_query()

    if results is not None:
        if hasattr(results, 'total') and results.total is not None and results.total > 0:
                flash(f"{results.total} result(s) found!", "notice")
        else:
            flash("No results found!", "box")
    return render_template(template, results=results, per_page=per_page,
                           q=query, deck_title_length=DECK_TITLE_LENGTH,
                           PER_PAGE_DECK=PER_PAGE_DECK, select=select)

@main.route("/toggle-theme")
def toggle_theme():
    url = request.referrer or request.host

    if not url_has_allowed_host_and_scheme(url , request.host):
        return abort(400)

    current_theme = session.get("theme")
    if current_theme == "dark":
        session["theme"] = "light"
    else:
        session["theme"] = "dark"
    return redirect(url)

@main.route("/remove")
def remove():
    return ""

@main.route('/contact-us', methods=['GET', 'POST'])
def contact_us():
    form = ContactUsForm()

    if form.validate_on_submit():

        if turnstile_verify():
            _contact = ContactUs()
            form.populate_obj(_contact)
            db.session.add(_contact)
            db.session.commit()
            flash('Thanks! We\'ll get back to you shortly!', 'success')
            return redirect(url_for('main.contact_us'))
        flash("🤖 Captcha verification failed ... Please reload the page and try again.", "error")

    if htmx:
        return render_template('partials/contact_us.html', form=form, htmx=htmx,
                               SITE_KEY=current_app.config['TURNSTILE_SITE_KEY'])
    return render_template('contact_us.html', form=form, htmx=htmx,
                           SITE_KEY=current_app.config['TURNSTILE_SITE_KEY'])

@main.route("/privacy")
def privacy():
    return render_template("/pdt/privacy.html")
@main.route("/disclaimer")
def disclaimer():
    return render_template("/pdt/disclaimer.html")
@main.route("/Terms-and-conditions")
def tac():
    return render_template("/pdt/tac.html")
@main.route("/about")
def about():
    return render_template("about.html")

src/posts/__init__.py
from .routes import posts

src/posts/routes.py
from flask import (render_template, url_for, flash, current_app,
                   redirect, request, Blueprint, abort, session)

from .forms import (PostForm, VoteForm, DeckForm,
                    LikeForm, UrlForm, ReportForm)

from ..models import Post, Deck, if_authorized, update_deck_last_modified

from ..main import ContactUs

from flask_login import login_required, current_user

from flask_htmx import make_response as htmx_make_response

from urllib import request as url_request

from ..extensions import db, htmx

from ..utils import get_user_id, rs, turnstile_verify, validate_table_fields

from ..modules.http import url_has_allowed_host_and_scheme

from ..constants import (
    CHOICES,
    PER_PAGE_POST,
    PER_PAGE_DECK,
    MAX_DECKS_PER_USER,
    MAX_POSTS_PER_DECK,
    DECK_FIELDS_LEN_MAX,
    DECK_DESCRIPTION_LEN_MAX,
)

posts = Blueprint('posts', __name__)

@posts.route("/decks", defaults={'page':1})
@posts.route("/decks/<int:page>")
@login_required
def decks(page):
    deck = Deck.query.filter_by(user_id=current_user.id).paginate(page=page, per_page=PER_PAGE_DECK)
    return render_template('decks.html', deck=deck, PER_PAGE_DECK=PER_PAGE_DECK)

@posts.route("/deck/<int:deck_id>", methods=["DELETE", "PUT", "GET"])
@login_required
def single_deck(deck_id):
    deck = if_authorized(deck_id)
    if request.method == "GET":
        return render_template("partials/edit_deck.html", deck=deck, CHOICES=CHOICES,
                               DECK_DESCRIPTION_LEN_MAX=DECK_DESCRIPTION_LEN_MAX,
                               form=DeckForm(deck_id=deck_id))
    elif request.method == "DELETE":
        db.session.delete(deck)
        db.session.commit()
        return '', 200
    elif request.method == "PUT":
            form=DeckForm()
            changes_made=False
            if form.validate_on_submit():
                if request.args.get('save') == "True":
                    field_names = ['deck_name', 'public', 'deck_description', 'category']
                    for field_name in field_names:
                        if field_name == 'public':
                            if form.public.data != deck.public:
                                public_value = True if form.public.data else False
                                setattr(deck, field_name, public_value)
                                changes_made = True
                        elif field_name in request.form and getattr(deck, field_name) != request.form[field_name]:
                            setattr(deck, field_name, rs(request.form[field_name]))
                            changes_made = True
                    if changes_made:
                        db.session.commit()
                return render_template("partials/deck_item.html", deck=deck)
            return render_template("partials/edit_deck.html", deck=deck, form=form, CHOICES=CHOICES,
                                   DECK_DESCRIPTION_LEN_MAX=DECK_DESCRIPTION_LEN_MAX)

@posts.route("/posts/<string:deck_id>/<string:post_id>/", methods=['GET', 'PUT', 'DELETE'])
@login_required
def edit_post(deck_id,post_id):
    deck = if_authorized(deck_id)
    post = Post.query.get(post_id)
    if not post or current_user.id != post.user_id:
        abort(403, "You are not allowed to perform any action on this post ...")
    form = PostForm()
    form.field.choices=deck.fields_choices()

    fields =  dict(post.__dict__)
    if request.method == "GET":
        if request.args.get('s') == "post-options":
            return render_template("partials/edit_post_options.html", post=post, deck=deck)
        return render_template("partials/edit_post.html", post=post, deck=deck, form=form)
    elif request.method == "DELETE":
        update_deck_last_modified(deck)
        db.session.delete(post)
        db.session.commit()
        return '', 200
    elif request.method == "PUT":
        if form.validate_on_submit():
            if request.args.get('save') == "True":
                for field_name in fields:
                    if field_name in request.form and getattr(post, field_name) != request.form[field_name]:
                        setattr(post, field_name, rs(request.form[field_name]))
                        update_deck_last_modified(deck)
                        db.session.commit()
            return render_template("partials/post_item.html", post=post, deck=deck, form=form)
        return render_template("partials/edit_post.html", post=post, deck=deck, form=form)

@posts.route("/add/<string:deck_id>", methods=['POST'], defaults={'deck_name':None})
@posts.route("/add/<string:deck_id>/<string:deck_name>")
def add(deck_id, deck_name):
    deck = if_authorized(deck_id)
    site_key=current_app.config['TURNSTILE_SITE_KEY']
    form = PostForm()

    form.field.choices = deck.fields_choices()
    if request.method == 'POST':
        if form.validate_on_submit():
            if get_user_id() == 1000 and not turnstile_verify():
                flash("Ooopsii Captcha verification failed ... 🤖 Please Try again!", "error")
                if htmx:
                    return render_template("partials/add.html", form=form, deck=deck, htmx=htmx)
                return render_template('add.html', form=form, deck=deck, htmx=htmx)

            if len(deck.posts) >= MAX_POSTS_PER_DECK:
                flash(f"This deck reached the maximum number of possible posts! Which is {MAX_POSTS_PER_DECK} posts per deck", "error")
                return redirect(url_for('posts.table', deck_id=deck.id, deck_name=deck.formatted_deck_name()))

            post = Post(
                user_id=get_user_id(),
                deck_id=deck_id,
                field=form.field.data,
                title=rs(form.title.data),
                description=rs(form.description.data),
                url=form.url.data
            )
            try:
                update_deck_last_modified(deck)
                db.session.add(post)
                db.session.commit()
                flash('Post created! Thanks for your contribution', 'success')
                return redirect(url_for('posts.table', deck_id=deck.id, deck_name=deck.formatted_deck_name()))
            except Exception as e:
                return f"{str(e)}"
    if htmx:
        return render_template("partials/add.html", form=form, deck=deck, htmx=htmx, site_key=site_key)
    return render_template('add.html', form=form, deck=deck, htmx=htmx, site_key=site_key)

@posts.route("/new", methods=['GET', 'POST'])
@login_required
def new():
    form = DeckForm()
    if form.validate_on_submit():

        if len(current_user.decks) >= MAX_DECKS_PER_USER:
            flash("You reached the maximum number of decks :/", "error")
            flash(f"You account can only have up to {MAX_DECKS_PER_USER} decks", "error")
            return redirect(url_for('posts.decks'))

        deck = Deck(
            user_id=current_user.id,
            deck_name=rs(form.deck_name.data),
            deck_description=rs(form.deck_description.data) if form.deck_description.data else '',
            category=rs(form.category.data),
            fields=rs(form.fields.data),
            public=form.public.data
        )
        try:
            db.session.add(deck)
            db.session.commit()
            flash('Deck added!', 'success')
            return redirect(url_for('posts.decks'))
        except:
            flash("There was a problem :/", "error")
    if htmx:
        return render_template("partials/new.html", form=form, htmx=htmx)
    return render_template("new.html", form=form, htmx=htmx,
                           DECK_FIELDS_LEN_MAX=DECK_FIELDS_LEN_MAX)

@posts.route('/tables/<string:deck_id>/', defaults={'page': 1, 'deck_name': None})
@posts.route('/tables/<string:deck_id>/<string:deck_name>', defaults={'page': 1})
@posts.route('/tables/<string:deck_id>/<string:deck_name>/<int:page>/')
def table(deck_id, deck_name, page):
    deck = if_authorized(deck_id)
    url = url_for('posts.table', deck_id=deck.id, deck_name=deck.formatted_deck_name())

    s = request.args.get('s')
    if s:
        if s == "table-options":
            return render_template("partials/table-options.html", deck=deck)
        elif s == "share":
            if deck.public:
                return render_template("partials/share.html", deck=deck)
            flash("This Deck is private! Please make sure you make it public if you wish to share it.", "notice")
            return htmx_make_response(location=url)

    form=PostForm()
    like=session.get(f'like-{deck.id}')
    unique_field_values, posts=Post.get_unique_field_per_page(deck_id)
    posts=posts.paginate(page=page, per_page=PER_PAGE_POST, error_out=False)

    if deck_name != deck.formatted_deck_name():
        return redirect(url)
    return render_template('user_tables.html', form=form, deck=deck, PER_PAGE_POST=PER_PAGE_POST,
                           posts=posts, like=like, unique_field_values=unique_field_values)

@posts.route("/rbtn", methods=["PUT"])
@login_required
def rbtn():
    fields = rs(request.form.get('fields'))

    if fields:
        try:
            validate_table_fields(fields)
            buttons = ''.join(f'<button class="m-8" disabled>{word}</button>' for word in fields.split())
            return render_template("partials/rbtn.html", buttons=buttons, l=len(fields.split()))
        except ValueError as e:
            return f"""<span class="ft">{str(e)}</span>"""
    abort(400)

@posts.route("/check-url", methods=["POST"])
def check_url():
    form=UrlForm()
    if form.validate_on_submit():
        url = request.form.get('url')
        try:
            req = url_request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
            with url_request.urlopen(req, timeout=5) as response:
                if response.status == 200:
                    return render_template("partials/url_status_success.html", status_code=200)
                else:

src/templates/decks.html
{% from 'macros/macros.html' import render_pagination %}

{% set title = "Your decks" %}
{% set description = "User private decks." %}
{% set keywords = "decks, personal decks, private decks" %} 

{% extends "layout.html" %}
{% block h1 %}
<h1>{{ title }}</h1>
{% include "search.html" %}
{% endblock h1 %}

{% block content %}
{% include "partials/nojs.html" %}
{% if deck.items %}
    <div class="flex-end topleft">
        <a href="{{ url_for('posts.new') }}"><button>New Deck</button></a>
    </div>
{% endif %}
<div id="decks" class="grid-container">
    {% for deck in deck.items %}
    {% include "partials/deck_item.html" %}
    {% endfor %}
</div>
{% if deck.items %}
    {% if deck.total - 1 >= PER_PAGE_DECK %}
    {{ render_pagination(deck, "posts.decks") }}
    {%endif%}
{% else %}
    <div class="centered-content">
        <p>No decks created yet.&nbsp;</p>
        <a href="{{ url_for('posts.new') }}">
            <button class="gray-button">Create a Deck</button>
        </a>
    </div>
{% endif %}
{% endblock %}

src/templates/home.html
{% from 'macros/macros.html' import render_field, render_decks, render_pagination %}
{% if filter_by %}
{% set title = filter_by %}
{% set description = "{{ filter_by }}: Discover curated {{ category }} decks filled with valuable resources for your journey." %}
{% set keywords = "{{ filter_by}}" %}
{% else %}
{% set title = "Pubic decks" %}
{% set description = "Public Decks: Embark on an Exciting Journey through a Curated Collection of Intriguing and Essential Resources." %}
{% set keywords = "Public decks" %}
{% endif %}
{% extends "layout.html" %}
{% block h1 %}
{% if filter_by %}
<h1>{{ filter_by }}</h1>
{% else %}
<h1>Rate it!</h1>
{% endif %}
<div class="centered-content">
    <form method="POST" action="/search">
        <input id="csrf_token" name="csrf_token" type="hidden" value="{{ csrf_token() }}">
        <input id="q" maxlength="100" minlength="2" name="q" placeholder="Search" required="" type="text" value="">
        <input type="hidden" name="select" id="select" value="deck_name">
        <input id="submit" name="submit" type="submit" value="Search">
    </form>
</div>
{% endblock h1 %}
{% block toc %}
<details class="toc side left">
    <summary>Filter by</summary>
    <div class="inner">
        <ul>
            {% for key,value in CHOICES.items() %}
            <li><a href="{{ url_for('main.filter_by', by=key) }}">{{ value }}</a></li>
            {% endfor %}
        </ul>
    </div>
</details>
{% endblock %}
{% block content %}
{{ render_decks(deck) }}
{% if deck.total is defined and deck.total - 1 >= PER_PAGE_DECK %}
{% if filter_by %}
{{ render_pagination(deck, 'main.filter_by', args={'by':filter_by}) }}
{% else %}
{{ render_pagination(deck, 'main.home') }}
{% endif %}
{% endif %}
{% endblock content %}

src/templates/layout.html
<!DOCTYPE html>
{% from "./macros/macros.html" import moon, sun %}
<html lang="en" class="{{ 'dark-mode' if session.get('theme') == 'dark'}}">
<head>
    <title>{{ title }} | Rate it</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="index,follow">
    <meta name="description" content="{{ description }}">
    <meta name="keywords" content="{{ keywords }}">
    <meta property="og:type" content= "website" />
    <meta property="og:url" content="{{ request.scheme }}://{{ request.host }}{{ request.path }}">
    <meta property="og:site_name" content="{{ title }}" />
    <meta property="og:description" content="{{ description }}">
    <meta property="og:image" content="{{ url_for('static', filename='img/_og.jpg') }}">
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:title" property="og:title" itemprop="name" content="{{ title }}"/>
    <meta name="twitter:domain" content="{{ request.scheme }}://{{ request.host }}{{ request.path }}"/>
    <meta name="twitter:description" property="og:description" itemprop="description" content="{{ description }}">
    <link rel="canonical" href="{{ request.scheme }}://{{ request.host }}{{ request.path }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style_min.css') }}">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/favicon.png') }}">
</head>
  <body>
    <header>
      <nav>
        <a href="{{ url_for('main.toggle_theme') }}" class="nav__link">
            <span class="nav__item">
                {% if session.get('theme') == "dark" %}
                    {{ sun("nav__icon") }}
                {% else %}
                    {{ moon("nav__icon") }}
                {% endif %}
            </span>
        </a>
        <a href="{{ url_for('main.home') }}">Home</a>
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('posts.decks') }}">My decks</a>
        <a id="user" href="{{ url_for('users.account') }}">
	      <img crossorigin="anonymous" height="24" width="24" loading="lazy" src="{{ current_user.gravatar(size=24) }}">
          <span>{{ current_user.username }}</span>
        </a>
        <a href="{{ url_for('users.logout') }}">Logout</a>
        {% else %}
        <a href="{{ url_for('users.login') }}">Login</a>
        <a href="{{ url_for('users.signup') }}">Signup</a>
        {% endif %}
      </nav>
      {% block h1 %}{% endblock %}
    </header>
    <main>
      {% block toc %}{% endblock %}
      {% include "partials/flash.html" %}
      <div id="htmx-flashed"></div>
      {% block content %}{% endblock %}
      <script nonce="random-csp-nonce" integrity="sha384-Hv9jfo+l0rygxyw/ETv4LDjxpzbla9THyfsaLw/h8Yt3SmZ9J1R/G6cIiXBnBU2e" src="{{ url_for('static', filename='js/htmx.js') }}"></script>
      <script nonce="random-csp-nonce" integrity="sha384-uvhGEC6b2nl9cr10jOonJSIQKMzvfFdX5+JvVUknBCmpJK0u7UpPkxh3T3HMDDNR" src="{{ url_for('static', filename='js/htmx-remove-me.js') }}"></script>
      {% block scripts %}{% endblock %}
    </main>
    <footer>
      <p>created by <a href="https://cschad.com">Cschad</a> and is licensed under the MIT license.<br>
      <a href="{{ url_for("main.contact_us")}}">Contact Us</a>
    </footer>
  </body>
</html>

src/templates/search_decks.html
{% from 'macros/macros.html' import render_pagination, render_decks, render_field %}

{% set title = "Search" %}
{% set description = "Search all the public decks. Filter by name, description or title." %}
{% set keywords = "search" %}

{% extends "layout.html" %}

{% block h1 %}
<h1>Search</h1>
{% include "search.html" %}
{% endblock %}

{% block content %}

{{ render_decks(results, DECK_TITLE_LENGTH) }}

{% if results.total is defined and results.total - 1 >= PER_PAGE_DECK %}
{{ render_pagination(results, 'main.search', args={'select':select, 'q':q}) }}
{% endif %}

{% endblock %}

src/templates/user_tables.html
{% from 'macros/macros.html' import render_pagination %}
{% extends "layout.html" %}

{% set title = deck.deck_name %}
{% set description = deck.deck_description %}
{% set keywords = deck.category %} 

{% block h1 %}
<h1>{{ deck.deck_name }}</h1>
{% if deck.deck_description %}
<p>{{ deck.deck_description }}</p>
{% endif %}
{% endblock h1 %}

{% block content %}

{% if current_user.is_authenticated %}
{% include "partials/nojs.html" %}
{% endif %}

<div class="tbadge">
    {% if deck.public == True %}
    <div class="is-small">
        Created by
        <div class="username">
          <img loading="lazy" crossorigin="anonymous" src="{{ deck.user.gravatar(size=25) }}" alt="{{deck.user.username}} Pic">
            {{ deck.user.username }}
        </div>
        <div class="date">
            {{ deck.creation_date | _pretty_date }}
        </div>
        | Public
    </div>
    {% else %}
    <div class="is-small">
        Created
        <div class="date">
            {{ deck.creation_date | _pretty_date }}
        </div>
        | Private
    </div>
    {% endif %}
    <div class="is-left">
        <a href="{{ url_for('posts.add', deck_id=deck.id, deck_name=deck.formatted_deck_name()) }}"
            hx-boost="true"
            hx-target="#form"
        >
        <svg class="circle no-border" height="45px" width="45px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M6 12H18M12 6V18" stroke="var(--accent)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        </a>
        <a
            hx-get="{{url_for('posts.table', deck_id=deck.id, deck_name=deck.formatted_deck_name(), s="table-options")}}"
            hx-target="this"
            hx-swap="afterend"
        >
        <svg class="circle no-border" height="45px" width="45px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M10 12a2 2 0 1 0 4 0 2 2 0 0 0-4 0zm0-6a2 2 0 1 0 4 0 2 2 0 0 0-4 0zm0 12a2 2 0 1 0 4 0 2 2 0 0 0-4 0z" fill="var(--accent)"/>
        </svg>
        </a>
    </div>
 </div>

<div id="form"></div>

{% include "partials/table.html" %}

{% if unique_field_values | length >= 2 %}
<div id="button-container">
    <div id="toc-floating-container">
        <input class="toggle" id="toc-toggle" type="checkbox">
        <label class="overlay" for="toc-toggle"></label>
        <label title="Toggle Table of Contents" for="toc-toggle" id="toc-button">
        <svg xmlns="http://www.w3.org/2000/svg" class="circle" fill="var(--accent)" viewBox="0 0 48 48"><path d="M8 21c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3zM8 9c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3zm0 24.33c-1.47 0-2.67 1.19-2.67 2.67s1.2 2.67 2.67 2.67 2.67-1.19 2.67-2.67-1.2-2.67-2.67-2.67zM14 38h28v-4H14v4zm0-12h28v-4H14v4zm0-16v4h28v-4H14z"/></svg>
        </label>
        <div class="toc-content">
            <div class="toc-container">
            {% for field in unique_field_values %}
                <ul>
                    <li>
                        <a href="#{{ field.lower() }}">{{ field }}</a>
                    </li>
                </ul>
            {% endfor %}
            </div>
        </div>
        <a title="Go to the top of the page" href="#" id="top-button">
            <svg class="circle" viewBox="0 0 20 20" fill="var(--accent)">
                <path d="M3.293 9.707a1 1 0 010-1.414l6-6a1 1 0 011.414 0l6 6a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L4.707 9.707a1 1 0 01-1.414 0z"></path>
            </svg>
        </a>
</div>
{% endif %}

{% endblock content %}