src/__init__.py
from flask import Flask, request, render_template, has_request_context

from werkzeug.exceptions import HTTPException

from .extensions import db, csrf, htmx, mail, login_manager, admin

from .utils import (pretty_date, get_random_urlsafe_string,
                    check_none_values)
from .config import config

from .users.routes import users
from .posts import posts
from .main import main

__all__ = ['create_app']

BLUEPRINTS = (
    posts,
    main,
    users
)

def create_app(config_name=None):

    blueprints = BLUEPRINTS

    app = Flask(__name__, instance_relative_config=True)

    configure_app(app, config_name)
    configure_extensions(app)
    configure_template_filters(app)
    configure_error_handlers(app)
    configure_blueprints(app, blueprints)

    return app

def configure_app(app, config_name=None):

    config_name = config_name or 'default'

    # A function that checks if there is an empty value in the config
    check_none_values(config[config_name])

    app.config.from_object(config[config_name])

    if hasattr(config[config_name], 'init_app'):
        config[config_name].init_app(app)

    print('=' * 10, f"> Running in {config_name} mode!\n")

def configure_template_filters(app):
    """
    A little cleanup after jinja template rendering
    : removing spaces, and striping new lines
    """
    app.jinja_env.trim_blocks = True
    app.jinja_env.lstrip_blocks = True
    strip_trailing_newlines = True

    @app.template_filter()
    def _pretty_date(value):
        return pretty_date(value)
    @app.template_filter()
    def format_date(value, format='%Y-%m-%d'):
        return value.strftime(format)

def configure_blueprints(app, blueprints):
    for blueprint in blueprints:
        app.register_blueprint(blueprint)

def configure_extensions(app):
    db.init_app(app)
    csrf.init_app(app)
    htmx.init_app(app)
    mail.init_app(app)
    admin.init_app(app)
    login_manager.init_app(app)

def configure_error_handlers(app):
    @app.errorhandler(Exception)
    def handle_error(error):
        if not isinstance(error, HTTPException):
            if not app.debug:
                return render_template('errors/500.html'), 500
            raise
        return render_template('errors/errors.html', error=error), error.code
    @app.errorhandler(404)
    def custom_error_404(error):
        return render_template('errors/404.html', error=error), error.code

src/main/__init__.py
from .routes import main
from .models import ContactUsView, ContactUs

src/main/routes.py
from flask import (render_template, request, Blueprint,
                   url_for, flash, abort, session, redirect, current_app)

from flask_login import current_user, user_logged_in

from flask_htmx import make_response as htmx_make_response

from .forms import ContactUsForm

from .models import ContactUs

from ..models import Deck, Post

from ..extensions import db, htmx

from ..modules.http import url_has_allowed_host_and_scheme

from ..utils import (get_user_id, validate_user_input,
                     turnstile_verify)

from sqlalchemy import or_

from ..constants import (
    DECK_TITLE_LENGTH,
    PER_PAGE_POST,
    PER_PAGE_DECK,
    QUERY_LEN_MAX,
    CHOICES
)

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/<int:page>")
def home(page=1):
    deck = Deck.query.filter_by(public=True).order_by(Deck.likes.desc()).\
        paginate(page=page, per_page=PER_PAGE_DECK)

    data = {
        'deck': deck,
        'CHOICES': CHOICES,
        'PER_PAGE_DECK': PER_PAGE_DECK,
        'DECK_TITLE_LENGTH': DECK_TITLE_LENGTH
    }

    return render_template("home.html", **data)

@main.route('/category/<string:by>', defaults={'page': 1})
@main.route("/category/<string:by>/<int:page>")
def filter_by(by=None, page=None):
    if by in CHOICES:
        deck = Deck.query.filter_by(public=True, category=by).\
            paginate(page=page, per_page=PER_PAGE_DECK)
        if not deck.items:
            flash(f"No deck in this Category found!", "notice")
        return render_template('home.html', deck=deck, CHOICES=CHOICES,
                               PER_PAGE_DECK=PER_PAGE_DECK,
                               DECK_TITLE_LENGTH=DECK_TITLE_LENGTH, filter_by=CHOICES[by])
    abort(404)

@main.route('/search/', defaults={'select': 'deck_name', 'page': 1}, methods=['GET', 'POST'])
@main.route('/search/<string:select>/', defaults={'page': 1})
@main.route('/search/<string:select>/<int:page>/')
def search(select, page):
    user_id = get_user_id()
    template="search_decks.html"
    results=None
    per_page=0

    if request.method == "GET":
        query = request.args.get("q", "None")
    elif request.method == "POST":
        select=request.form.get("select")
        query = request.form.get("q", "None")

    try:
        validate_user_input(query, QUERY_LEN_MAX)
    except Exception as e:
        flash(str(e), "error")

    def deck_query():
        global PER_PAGE_DECK
        return per_page, Deck.query.filter(
            (Deck.public == True) | (Deck.user_id == user_id),
            Deck.deck_name.ilike(f'%{query}%')
        ).paginate(page=page, per_page=PER_PAGE_DECK)
    def post_query():
        global PER_PAGE_POST
        return per_page,(
            Post.query
            .join(Deck)
            .filter(
                (Deck.public == True) | (Deck.user_id == user_id),
                or_(
                    (select == 'title' and Post.title.ilike(f'%{query}%')),
                    (select == 'description' and Post.description.ilike(f'%{query}%'))
                )
            )
            .paginate(page=page, per_page=PER_PAGE_POST)
        )

    if select == 'deck_name':
        per_page, results = deck_query()
        template='search_decks.html'
    elif select in ['title', 'description']:
        template='search_posts.html'
        per_page, results = post_query()

    if results is not None:
        if hasattr(results, 'total') and results.total is not None and results.total > 0:
                flash(f"{results.total} result(s) found!", "notice")
        else:
            flash("No results found!", "box")
    return render_template(template, results=results, per_page=per_page,
                           q=query, deck_title_length=DECK_TITLE_LENGTH,
                           PER_PAGE_DECK=PER_PAGE_DECK, select=select)

@main.route("/toggle-theme")
def toggle_theme():
    url = request.referrer or request.host

    if not url_has_allowed_host_and_scheme(url , request.host):
        return abort(400)

    current_theme = session.get("theme")
    if current_theme == "dark":
        session["theme"] = "light"
    else:
        session["theme"] = "dark"
    return redirect(url)

@main.route("/remove")
def remove():
    return ""

@main.route('/contact-us', methods=['GET', 'POST'])
def contact_us():
    form = ContactUsForm()

    if form.validate_on_submit():

        if turnstile_verify():
            _contact = ContactUs()
            form.populate_obj(_contact)
            db.session.add(_contact)
            db.session.commit()
            flash('Thanks! We\'ll get back to you shortly!', 'success')
            return redirect(url_for('main.contact_us'))
        flash("🤖 Captcha verification failed ... Please reload the page and try again.", "error")

    if htmx:
        return render_template('partials/contact_us.html', form=form, htmx=htmx,
                               SITE_KEY=current_app.config['TURNSTILE_SITE_KEY'])
    return render_template('contact_us.html', form=form, htmx=htmx,
                           SITE_KEY=current_app.config['TURNSTILE_SITE_KEY'])

@main.route("/privacy")
def privacy():
    return render_template("/pdt/privacy.html")
@main.route("/disclaimer")
def disclaimer():
    return render_template("/pdt/disclaimer.html")
@main.route("/Terms-and-conditions")
def tac():
    return render_template("/pdt/tac.html")
@main.route("/about")
def about():
    return render_template("about.html")

src/posts/__init__.py
from .routes import posts

src/posts/routes.py
from flask import (render_template, url_for, flash, current_app,
                   redirect, request, Blueprint, abort, session)

from .forms import (PostForm, VoteForm, DeckForm,
                    LikeForm, UrlForm, ReportForm)

from ..models import Post, Deck, if_authorized, update_deck_last_modified

from ..main import ContactUs

from flask_login import login_required, current_user

from flask_htmx import make_response as htmx_make_response

from urllib import request as url_request

from ..extensions import db, htmx

from ..utils import get_user_id, rs, turnstile_verify, validate_table_fields

from ..modules.http import url_has_allowed_host_and_scheme

from ..constants import (
    CHOICES,
    PER_PAGE_POST,
    PER_PAGE_DECK,
    MAX_DECKS_PER_USER,
    MAX_POSTS_PER_DECK,
    DECK_FIELDS_LEN_MAX,
    DECK_DESCRIPTION_LEN_MAX,
)

posts = Blueprint('posts', __name__)

@posts.route("/decks", defaults={'page':1})
@posts.route("/decks/<int:page>")
@login_required
def decks(page):
    deck = Deck.query.filter_by(user_id=current_user.id).paginate(page=page, per_page=PER_PAGE_DECK)
    return render_template('decks.html', deck=deck, PER_PAGE_DECK=PER_PAGE_DECK)

@posts.route("/deck/<int:deck_id>", methods=["DELETE", "PUT", "GET"])
@login_required
def single_deck(deck_id):
    deck = if_authorized(deck_id)
    if request.method == "GET":
        return render_template("partials/edit_deck.html", deck=deck, CHOICES=CHOICES,
                               DECK_DESCRIPTION_LEN_MAX=DECK_DESCRIPTION_LEN_MAX,
                               form=DeckForm(deck_id=deck_id))
    elif request.method == "DELETE":
        db.session.delete(deck)
        db.session.commit()
        return '', 200
    elif request.method == "PUT":
            form=DeckForm()
            changes_made=False
            if form.validate_on_submit():
                if request.args.get('save') == "True":
                    field_names = ['deck_name', 'public', 'deck_description', 'category']
                    for field_name in field_names:
                        if field_name == 'public':
                            if form.public.data != deck.public:
                                public_value = True if form.public.data else False
                                setattr(deck, field_name, public_value)
                                changes_made = True
                        elif field_name in request.form and getattr(deck, field_name) != request.form[field_name]:
                            setattr(deck, field_name, rs(request.form[field_name]))
                            changes_made = True
                    if changes_made:
                        db.session.commit()
                return render_template("partials/deck_item.html", deck=deck)
            return render_template("partials/edit_deck.html", deck=deck, form=form, CHOICES=CHOICES,
                                   DECK_DESCRIPTION_LEN_MAX=DECK_DESCRIPTION_LEN_MAX)

@posts.route("/posts/<string:deck_id>/<string:post_id>/", methods=['GET', 'PUT', 'DELETE'])
@login_required
def edit_post(deck_id,post_id):
    deck = if_authorized(deck_id)
    post = Post.query.get(post_id)
    if not post or current_user.id != post.user_id:
        abort(403, "You are not allowed to perform any action on this post ...")
    form = PostForm()
    form.field.choices=deck.fields_choices()

    fields =  dict(post.__dict__)
    if request.method == "GET":
        if request.args.get('s') == "post-options":
            return render_template("partials/edit_post_options.html", post=post, deck=deck)
        return render_template("partials/edit_post.html", post=post, deck=deck, form=form)
    elif request.method == "DELETE":
        update_deck_last_modified(deck)
        db.session.delete(post)
        db.session.commit()
        return '', 200
    elif request.method == "PUT":
        if form.validate_on_submit():
            if request.args.get('save') == "True":
                for field_name in fields:
                    if field_name in request.form and getattr(post, field_name) != request.form[field_name]:
                        setattr(post, field_name, rs(request.form[field_name]))
                        update_deck_last_modified(deck)
                        db.session.commit()
            return render_template("partials/post_item.html", post=post, deck=deck, form=form)
        return render_template("partials/edit_post.html", post=post, deck=deck, form=form)

@posts.route("/add/<string:deck_id>", methods=['POST'], defaults={'deck_name':None})
@posts.route("/add/<string:deck_id>/<string:deck_name>")
def add(deck_id, deck_name):
    deck = if_authorized(deck_id)
    site_key=current_app.config['TURNSTILE_SITE_KEY']
    form = PostForm()

    form.field.choices = deck.fields_choices()
    if request.method == 'POST':
        if form.validate_on_submit():
            if get_user_id() == 1000 and not turnstile_verify():
                flash("Ooopsii Captcha verification failed ... 🤖 Please Try again!", "error")
                if htmx:
                    return render_template("partials/add.html", form=form, deck=deck, htmx=htmx)
                return render_template('add.html', form=form, deck=deck, htmx=htmx)

            if len(deck.posts) >= MAX_POSTS_PER_DECK:
                flash(f"This deck reached the maximum number of possible posts! Which is {MAX_POSTS_PER_DECK} posts per deck", "error")
                return redirect(url_for('posts.table', deck_id=deck.id, deck_name=deck.formatted_deck_name()))

            post = Post(
                user_id=get_user_id(),
                deck_id=deck_id,
                field=form.field.data,
                title=rs(form.title.data),
                description=rs(form.description.data),
                url=form.url.data
            )
            try:
                update_deck_last_modified(deck)
                db.session.add(post)
                db.session.commit()
                flash('Post created! Thanks for your contribution', 'success')
                return redirect(url_for('posts.table', deck_id=deck.id, deck_name=deck.formatted_deck_name()))
            except Exception as e:
                return f"{str(e)}"
    if htmx:
        return render_template("partials/add.html", form=form, deck=deck, htmx=htmx, site_key=site_key)
    return render_template('add.html', form=form, deck=deck, htmx=htmx, site_key=site_key)

@posts.route("/new", methods=['GET', 'POST'])
@login_required
def new():
    form = DeckForm()
    if form.validate_on_submit():

        if len(current_user.decks) >= MAX_DECKS_PER_USER:
            flash("You reached the maximum number of decks :/", "error")
            flash(f"You account can only have up to {MAX_DECKS_PER_USER} decks", "error")
            return redirect(url_for('posts.decks'))

        deck = Deck(
            user_id=current_user.id,
            deck_name=rs(form.deck_name.data),
            deck_description=rs(form.deck_description.data) if form.deck_description.data else '',
            category=rs(form.category.data),
            fields=rs(form.fields.data),
            public=form.public.data
        )
        try:
            db.session.add(deck)
            db.session.commit()
            flash('Deck added!', 'success')
            return redirect(url_for('posts.decks'))
        except:
            flash("There was a problem :/", "error")
    if htmx:
        return render_template("partials/new.html", form=form, htmx=htmx)
    return render_template("new.html", form=form, htmx=htmx,
                           DECK_FIELDS_LEN_MAX=DECK_FIELDS_LEN_MAX)

@posts.route('/tables/<string:deck_id>/', defaults={'page': 1, 'deck_name': None})
@posts.route('/tables/<string:deck_id>/<string:deck_name>', defaults={'page': 1})
@posts.route('/tables/<string:deck_id>/<string:deck_name>/<int:page>/')
def table(deck_id, deck_name, page):
    deck = if_authorized(deck_id)
    url = url_for('posts.table', deck_id=deck.id, deck_name=deck.formatted_deck_name())

    s = request.args.get('s')
    if s:
        if s == "table-options":
            return render_template("partials/table-options.html", deck=deck)
        elif s == "share":
            if deck.public:
                return render_template("partials/share.html", deck=deck)
            flash("This Deck is private! Please make sure you make it public if you wish to share it.", "notice")
            return htmx_make_response(location=url)

    form=PostForm()
    like=session.get(f'like-{deck.id}')
    unique_field_values, posts=Post.get_unique_field_per_page(deck_id)
    posts=posts.paginate(page=page, per_page=PER_PAGE_POST, error_out=False)

    if deck_name != deck.formatted_deck_name():
        return redirect(url)
    return render_template('user_tables.html', form=form, deck=deck, PER_PAGE_POST=PER_PAGE_POST,
                           posts=posts, like=like, unique_field_values=unique_field_values)

@posts.route("/rbtn", methods=["PUT"])
@login_required
def rbtn():
    fields = rs(request.form.get('fields'))

    if fields:
        try:
            validate_table_fields(fields)
            buttons = ''.join(f'<button class="m-8" disabled>{word}</button>' for word in fields.split())
            return render_template("partials/rbtn.html", buttons=buttons, l=len(fields.split()))
        except ValueError as e:
            return f"""<span class="ft">{str(e)}</span>"""
    abort(400)

@posts.route("/check-url", methods=["POST"])
def check_url():
    form=UrlForm()
    if form.validate_on_submit():
        url = request.form.get('url')
        try:
            req = url_request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
            with url_request.urlopen(req, timeout=5) as response:
                if response.status == 200:
                    return render_template("partials/url_status_success.html", status_code=200)
                else:

src/templates/partials/edit_deck.html
<div class="grid-item float pf" id="deck-{{deck.id}}">
    <form hx-target="#deck-{{deck.id}}" hx-swap="outerHTML" hx-put="{{ url_for('posts.single_deck', deck_id=deck.id, save=True) }}">
        {{ form.csrf_token }}
        <input type="hidden" name="fields" id="fields" value="{{ deck.fields }}">
        {% if form.fields.errors %}
            <div class="form-error">
                {% for error in form.fields.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
        {{ form.deck_name(value=form.deck_name.data or deck.deck_name) }}
        {% if form.deck_name.errors %}
            <div class="form-error">
                {% for error in form.deck_name.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
        <textarea id="deck_description"
                  maxlength="{{ DECK_DESCRIPTION_LEN_MAX }}"
                  placeholder="Deck description"
                  name="deck_description">{{ form.deck_description.data or deck.deck_description or '' }}</textarea>
        {% if form.deck_description.errors %}
        <div class="form-error">
            {% for error in form.deck_description.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% endif %}
        <div class="block">
            <select name="category">
            {% for key,value in CHOICES.items() %}
            <option value="{{ key }}" {% if key == deck.category %}selected{% endif %}>{{ value }}</option>
            {% endfor %}
            </select>
        </div>
        {% if form.category.errors %}
        <div class="form-error">
            {% for error in form.category.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% endif %}
        <div class="block m-8">
            <input id="checkbox-public" class="toggle-checkbox" value="True" name="public" type="checkbox" id="public" {% if deck.public %}checked{% endif %}>
            <span class="toggle-label">Public</span>
        </div>
        {{ form.submit(value="Save") }}
        <div class="button gray-button gbf"
        hx-put="{{ url_for('posts.single_deck', deck_id=deck.id, save=False) }}"
        hx-swap="outerHTML"
        hx-target="#deck-{{deck.id}}"
        >
        cancel
        </div>
    </form>
</div>

src/templates/partials/edit_post.html
<div class="grid-item float pf rel" id="edit-{{post.id}}">
  <form hx-put="{{ url_for('posts.edit_post',deck_id=deck.id, post_id=post.id, save=True) }}" hx-target="#row-{{post.id}}">
        {{ form.csrf_token }}
        {{ form.title(value=post.title) }}
        {% if form.title.errors %}
            <div class="form-error">
                {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
        <textarea id="description" maxlength="{{POST_DESCRIPTION_LEN_MAX}}" name="description" required>{{ post.description }}</textarea>
        {% if form.description.errors %}
            <div id="form-errors" class="form-error">
                {% for error in form.description.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
        <input 
          id="url" maxlength="500" name="url" required="" type="text" value="{{post.url}}"
          hx-trigger="keyup changed delay:600ms"
          hx-indicator="#spinner"
          hx-target="#url-status"
          hx-post="{{ url_for('posts.check_url') }}"
        >
        <div id="url-status"></div>
        <img  height="25px" width="25px" id="spinner" class="spinner" src="{{ url_for('static', filename='img/loading.svg') }}"/>
        {% if form.url.errors %}
            <div class="form-error">
                {% for error in form.url.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
        <div class="block m-8">
          <select id="{{ form.field.id }}" name="{{ form.field.name }}" placeholder="{{ form.field.placeholder }}">
              {% for option_value, option_label in form.field.choices %}
              <option value="{{ option_value }}" {% if option_value == post.field %}selected{% endif %}>{{ option_label }}</option>
              {% endfor %}
          </select>
        </div>

        {{ form.submit(value="Save") }}
        <div class="button gray-button gbf"
        hx-put="{{ url_for('posts.edit_post',deck_id=deck.id, post_id=post.id, save=False) }}"
        hx-target="#row-{{post.id}}"
        >
        cancel
        </div>
    </form>
</div>

src/templates/partials/edit_post_options.html
<div hx-ext="remove-me" remove-me="" class="pr">
    <div class="dropdown-content t-options pa">
        <div class="dropdown-item" 
            hx-target="#row-{{post.id}}"
            hx-get="{{ url_for('posts.edit_post',deck_id=deck.id, post_id=post.id) }}"
            >
            <div class="edit"></div>
            Edit
        </div>
        <div class="dropdown-item"
             hx-delete="{{ url_for('posts.edit_post',deck_id=deck.id, post_id=post.id) }}"
             hx-target="#row-{{post.id}}"
             hx-vals='{"csrf_token": "{{csrf_token()}}"}'
             hx-swap="outerHTML swap:0.4s"
        >
        <div class="remove"></div>
        Remove
        </div>
    </div>
</div>

src/templates/partials/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
 {% for category, message in messages %}
  <div hx-ext="remove-me" remove-me="3s" id="_flash">
    <div class="box pr {{ category }}">
    <div class="top-right m-10 hover-scale close-flash"
      hx-get="{{ url_for('main.remove') }}"
      htmx-swapping="#_flash"
      hx-swap="delete"
      hx-target="#_flash"
    >&#x2716;</div>
      {{ message | safe }}
    </div>
    <br>
  </div>
 {% endfor %}
{% endif %}
{% endwith %}

src/templates/partials/nojs.html
<noscript>
    <div class="notice box">
        Please enable javascript
    </div>
    <div class="date p-10 m-8">
        This website uses only
        <a href="https://htmx.org"><strong><u>htmx</u></strong></a>
        Read more in the <a href="{{ url_for('main.privacy')}}">privacy policy</a>
    </div>

</noscript>

src/templates/partials/post_item.html
<!-- {% if deck.public %} -->
<!-- <td> -->
<!--     <div class="vote-container" id="vote-container-{{ post.id }}"> -->
<!--         <div class="count hover-scale" hx-target="#row-id-{{ post.id }}" hx-swap="innerHTML" hx-put="{{ url_for('posts.vote', post_id=post.id, vote_type=1) }}">▲</div> -->
<!--             <span class="count" id="row-id-{{ post.id }}">{{ post.votes }}</span> -->
<!--         <div class="count hover-scale" hx-target="#row-id-{{ post.id }}" hx-swap="innerHTML" hx-put="{{ url_for('posts.vote', post_id=post.id, vote_type=0) }}">▼</div> -->
<!--     </div> -->
<!-- </td> -->
<!-- {% endif %} -->

<td><a href="{{ post.url }}">{{ post.title }}</a></td>
<td>
    <div class="flex-end">
    {{ post.description }}
        <div class="flex-end is-left">
            {% if post.user_id == current_user.id %}
            <div id="btn-{{post.id}}" class="options"
                 hx-get="{{ url_for('posts.edit_post',deck_id=deck.id, post_id=post.id, s='post-options') }}"
                 hx-target="this"
                 hx-swap="afterend"
            >..</div>
            {% endif %}
        </div>
     </div>
</td>

src/templates/partials/post_item_helper.html
<tr id="row-{{ post.id }}">
  <td><a href="{{ post.url }}">{{ post.title }}</a></td>
  <td>
      <div class="flex-end">
      {{ post.description }}
          <div class="flex-end is-left">
              {% if deck.user_id == current_user.id %}
              <div id="btn-{{post.id}}" class="options hover-scale"
                   hx-get="{{ url_for('posts.edit_post',deck_id=deck.id, post_id=post.id, s='options') }}"
                   hx-target="this"
                   hx-swap="afterend"
              ></div>
              {% endif %}
          </div>
       </div>
  </td>
</tr>
<tr id="last_node_{{post.field}}"></tr>

src/templates/partials/rbtn.html
{{buttons | safe}}
<div class="box p-10">
    <span class="is-small"><strong>Note: </strong>Each field will be a table name! You have {{l}} so far :)</span>
</div>

src/templates/partials/share.html
{% set url = request.scheme ~ '://' ~ request.host ~ url_for('posts.table', deck_id=deck.id, deck_name=deck.formatted_deck_name()) %}
{% set title = deck.deck_name %}
{% set description = deck.deck_description %}
{% set keywords = deck.category %} 
<div class="grid-item float pf rel" id="share">
  <div class="top-right m-10 hover-scale close-flash"
    hx-get="{{ url_for('main.remove') }}"
    htmx-swapping="#share"
    hx-swap="delete"
    hx-target="#share"
  >&#x2716;</div>
<div>
    <div class="share-buttons">
        <a target="_blank" rel="noopener noreferrer" aria-label="share {{ title }} on twitter"
            href="https://twitter.com/intent/tweet/?text={{ title }}&amp;url={{ url }}&amp;hashtags={{ keywords }}">
             <img src="{{ url_for('static', filename='img/twitter.svg') }}" alt="Twitter Logo" loading="lazy">
        </a>
        <a target="_blank" rel="noopener noreferrer" aria-label="share {{ title }} on linkedin"
            href="https://www.linkedin.com/shareArticle?mini=true&amp;url={{ url }}&amp;title={{ title }}&amp;summary={{ description }}&amp;source={{ url }}">
            <img src="{{ url_for('static', filename='img/linkedin.svg') }}" alt="Linkedin Logo" loading="lazy">
        </a>
        <a target="_blank" rel="noopener noreferrer" aria-label="share {{ title }} on reddit"
            href="https://reddit.com/submit?url={{ url }}&title={{ title }}">
            <img src="{{ url_for('static', filename='img/reddit.svg') }}" alt="Reddit Logo" loading="lazy">
        </a>
        <a target="_blank" rel="noopener noreferrer" aria-label="share {{ title }} on facebook"
            href="https://facebook.com/sharer/sharer.php?u={{ url }}">
            <img src="{{ url_for('static', filename='img/facebook.svg') }}" alt="Facebook Logo" loading="lazy">
        </a>
        <a target="_blank" rel="noopener noreferrer" aria-label="share {{ url }} on whatsapp"
            href="https://api.whatsapp.com/send?text={{ title }}%20-%20{{ url }}">
            <img src="{{ url_for('static', filename='img/whatsapp.svg') }}" alt="Whatsapp Logo" loading="lazy">
        </a>
        <a target="_blank" rel="noopener noreferrer" aria-label="share {{ title }} on telegram"
            href="https://telegram.me/share/url?text={{ title }}&amp;url={{ url }}">
            <img src="{{ url_for('static', filename='img/telegram.svg') }}" alt="Telegram Logo" loading="lazy">
        </a>
    </div>
    <input class="m-8" type="input" value="{{ url }}">
</div>

src/templates/partials/url_status.html
{% if error_message %}
<div class="form-error">
  <span>⚠️ {{ error_message }}</span>
</div>
{% endif %}

src/templates/partials/url_status_success.html
<div class="st">✔️  Valid URL response</div>